---
build:
  image: alexzorin/libvirt-go_test:1.2
  commands:
    - go test -v

notify:
  slack:
    webhook_url: $$SLACK_URL
    channel: $$SLACK_CHANNEL
    when:
      started: true
      success: true
      failure: true

publish:
  github_release:
    api_key: $$GITHUB_RELEASE_TOKEN
  when:
    event: tag
    branch: master
